name: Package
definition: A class to describe a package.
since_version: '2.0'

fields:
- primary_noun: Identifier
  type: Identifier
  definition: An identifier for this package.
  cardinality: 0..1
  since_version: '2.0'
- primary_noun: Quantity
  type: Quantity
  definition: The quantity of items contained in this package.
  cardinality: 0..1
  since_version: '2.0'
- primary_noun: Indicator
  type: Indicator
  definition: An indicator that the packaging material is returnable (true) or not (false).
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Package Level
  primary_noun: Code
  type: Code
  definition: A code signifying a level of packaging.
  untded_code: '7075'
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Packaging Type
  primary_noun: Code
  type: Code
  definition: A code signifying a type of packaging.
  alternative_business_terms: Package classification code
  untded_code: '7065'
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Packaging
  primary_noun: Type
  type: Text
  definition: The type of packaging, described as a text.
  cardinality: 0..n
  since_version: '2.3'
- possessive_noun: Packing
  primary_noun: Material
  type: Text
  definition: Text describing the packaging material.
  untded_code: '7064'
  cardinality: 0..n
  since_version: '2.0'
- primary_noun: Identifier
  type: Identifier
  definition: An identifier for use in tracing this package, such as the EPC number used in RFID.
  cardinality: 0..1
  since_version: '2.1'

objects:
- qualifier: Contained
  type: Package
  definition: A package contained within this package.
  cardinality: 0..n
  since_version: '2.0'
- qualifier: Containing
  type: Transport Equipment
  definition: The piece of transport equipment containing this package.
  cardinality: 0..1
  since_version: '2.1'
- type: Goods Item
  definition: A goods item included in this package.
  cardinality: 0..n
  since_version: '2.0'
- qualifier: Measurement
  type: Dimension
  definition: A measurable dimension (length, mass, weight, or volume) of this package.
  cardinality: 0..n
  since_version: '2.0'
- type: Delivery Unit
  definition: A delivery unit within this package.
  cardinality: 0..n
  since_version: '2.0'
- type: Delivery
  definition: The delivery of this package.
  cardinality: 0..1
  since_version: '2.1'
- type: Pickup
  definition: The pickup of this package.
  cardinality: 0..1
  since_version: '2.1'
- type: Despatch
  definition: The despatch of this package.
  cardinality: 0..1
  since_version: '2.1'
- type: Status
  definition: The status of this transport handling unit.
  cardinality: 0..n
  since_version: '2.4'
