name: Application Response
definition: A document to indicate the application's response to a transaction. This may be a business response initiated by a user or a technical response sent automatically by an application.
since_version: '2.0'

fields:
- possessive_noun: UBL Version
  primary_noun: Identifier
  type: Identifier
  definition: Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.
  examples: 2.0.5
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Customization
  primary_noun: Identifier
  type: Identifier
  definition: Identifies a user-defined customization of UBL for a specific use.
  examples: NES
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Profile
  primary_noun: Identifier
  type: Identifier
  definition: Identifies a user-defined profile of the customization of UBL being used.
  examples: BasicProcurementProcess
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Profile Execution
  primary_noun: Identifier
  type: Identifier
  definition: Identifies an instance of executing a profile, to associate all transactions in a collaboration.
  examples: BPP-1001
  cardinality: 0..1
  since_version: '2.1'
- primary_noun: Identifier
  type: Identifier
  definition: An identifier for this document, assigned by the sender.
  cardinality: '1'
  since_version: '2.0'
- primary_noun: UUID
  type: Identifier
  definition: A universally unique identifier for an instance of this document.
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Issue
  primary_noun: Date
  type: Date
  definition: The date, assigned by the sender, on which this document was issued.
  cardinality: '1'
  since_version: '2.0'
- possessive_noun: Issue
  primary_noun: Time
  type: Time
  definition: The time, assigned by the sender, at which this document was issued.
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Response
  primary_noun: Date
  type: Date
  definition: The date on which the information in the response was created.
  cardinality: 0..1
  since_version: '2.0'
- possessive_noun: Response
  primary_noun: Time
  type: Time
  definition: The time at which the information in the response was created.
  cardinality: 0..1
  since_version: '2.0'
- primary_noun: Note
  type: Text
  definition: Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.
  cardinality: 0..n
  since_version: '2.0'
- primary_noun: Version
  type: Identifier
  definition: Identifies the current version of this document.
  cardinality: 0..1
  since_version: '2.0'

objects:
- type: Signature
  definition: A signature applied to this document.
  cardinality: 0..n
  since_version: '2.0'
- qualifier: Sender
  type: Party
  definition: The party sending this document.
  cardinality: '1'
  since_version: '2.0'
- qualifier: Receiver
  type: Party
  definition: The party receiving this document.
  cardinality: '1'
  since_version: '2.0'
- type: Document Response
  definition: A response to a document.
  cardinality: 0..n
  since_version: '2.0'
